# ================= APPLICATION NAME =================
spring.application.name=storage-local-emulator

server.port=8081

info.app.name=Storage Local Emulator
info.app.version=0.0.1
info.app.description=Local object storage emulator with signed URL support
management.info.env.enabled=true

# ================= JDBC / DataSource =================
spring.datasource.url=jdbc:sqlite:${storage.emulator.root.path}/db/storage_metadata.db?foreign_keys=on&busy_timeout=5000&journal_mode=WAL&synchronous=NORMAL
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:/db/schema.sql

logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.com.vicente.storage=debug

# ================= ACTUATOR =================
# Expõe apenas endpoints essenciais para o emulator
management.endpoints.web.exposure.include=health,info,metrics,loggers,circuitbreakers,ratelimiters,mappings

# Mostrar detalhes completos na saúde
management.endpoint.health.show-details=always

# Ativa health check de circuit breaker e rate limiter (Resilience4j)
management.health.circuitbreakers.enabled=true
management.health.ratelimiters.enabled=true

# ================= METRICS =================
# Ativa métricas básicas de JVM, process e JDBC
management.metrics.enable.jvm=true
management.metrics.enable.system=true
management.metrics.enable.jdbc=true


# Adiciona tags padrão (útil para logging/monitoramento centralizado)
management.metrics.tags.application=${spring.application.name}

# ================= SECURITY =================
# Limitar acesso ao actuator
spring.security.user.name=admin
spring.security.user.password=${USER_PASSWORD}


storage.emulator.root.path=var/lib/data
storage.emulator.root.master-key.rotation-months=2
storage.emulator.root.access-key=${STORAGE_ROOT_KEY_ID}
storage.emulator.root.secret-key=${STORAGE_ROOT_SECRET_KEY}

spring.config.import=optional:resilience.yml

# Tamanho máximo de um único arquivo
spring.servlet.multipart.max-file-size=500MB
# Tamanho máximo da requisição total (arquivo + metadados JSON)
spring.servlet.multipart.max-request-size=505MB
