spring.application.name=storage-local-emulator

# ================= JDBC / DataSource =================
# URL de conexão JDBC para o banco SQLite.
# './data/storage.db' indica que o arquivo do banco estará na pasta 'data' relativa ao diretório do projeto.
spring.datasource.url=jdbc:sqlite:./data/storage_metadata.db

# Driver JDBC que será usado pelo Spring Boot para se conectar ao SQLite.
# O driver 'org.sqlite.JDBC' é o padrão para SQLite.
spring.datasource.driver-class-name=org.sqlite.JDBC

#logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG

# Pool HikariCP
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:/db/schema.sql